-- MySQL Script generated by MySQL Workbench
-- Thu Nov 25 20:42:41 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `correo` VARCHAR(45) NOT NULL,
  `usuario` VARCHAR(10) NOT NULL,
  `contrasena` VARCHAR(15) NOT NULL,
  `privilegio` VARCHAR(7) NOT NULL,
  PRIMARY KEY (`idUsuario`),
  UNIQUE INDEX `usuario_UNIQUE` (`usuario` ASC) VISIBLE,
  UNIQUE INDEX `correo_UNIQUE` (`correo` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Libro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Libro` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Libro` (
  `idLibro` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `autor` VARCHAR(45) NOT NULL,
  `anio` VARCHAR(4) NOT NULL,
  `edicion` VARCHAR(45) NOT NULL,
  `ISBN` VARCHAR(20) NOT NULL,
  `categoria` VARCHAR(45) NOT NULL,
  `id_imagen` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idLibro`),
  UNIQUE INDEX `ISBN_UNIQUE` (`ISBN` ASC) VISIBLE,
  UNIQUE INDEX `id_imagen_UNIQUE` (`id_imagen` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Prestamo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Prestamo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Prestamo` (
  `idPrestamo` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  `Libro_idLibro` INT NOT NULL,
  PRIMARY KEY (`idPrestamo`),
  INDEX `fk_Prestamo_Usuario1_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  INDEX `fk_Prestamo_Libro1_idx` (`Libro_idLibro` ASC) VISIBLE,
  CONSTRAINT `fk_Prestamo_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Prestamo_Libro1`
    FOREIGN KEY (`Libro_idLibro`)
    REFERENCES `mydb`.`Libro` (`idLibro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`detallePrestamo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`detallePrestamo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`detallePrestamo` (
  `id_detallePrestamo` INT NOT NULL AUTO_INCREMENT,
  `fecha_devolucion` DATE NOT NULL,
  `fecha_entrega` DATE NOT NULL,
  `Prestamo_idPrestamo` INT NOT NULL,
  PRIMARY KEY (`id_detallePrestamo`),
  INDEX `fk_detallePrestamo_Prestamo1_idx` (`Prestamo_idPrestamo` ASC) VISIBLE,
  CONSTRAINT `fk_detallePrestamo_Prestamo1`
    FOREIGN KEY (`Prestamo_idPrestamo`)
    REFERENCES `mydb`.`Prestamo` (`idPrestamo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Autor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Autor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Autor` (
  `idAutor` INT NOT NULL,
  `nombres` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAutor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Autor_has_Libro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Autor_has_Libro` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Autor_has_Libro` (
  `Autor_idAutor` INT NOT NULL,
  `Libro_idLibro` INT NOT NULL,
  PRIMARY KEY (`Autor_idAutor`, `Libro_idLibro`),
  INDEX `fk_Autor_has_Libro_Libro1_idx` (`Libro_idLibro` ASC) VISIBLE,
  INDEX `fk_Autor_has_Libro_Autor1_idx` (`Autor_idAutor` ASC) VISIBLE,
  CONSTRAINT `fk_Autor_has_Libro_Autor1`
    FOREIGN KEY (`Autor_idAutor`)
    REFERENCES `mydb`.`Autor` (`idAutor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Autor_has_Libro_Libro1`
    FOREIGN KEY (`Libro_idLibro`)
    REFERENCES `mydb`.`Libro` (`idLibro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
